name: GitHub Actions Demo
on:
  push:
    tags:
      - '*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build apk
        run: ./scripts/build.sh

      - uses: actions/upload-artifact@v2
        with:
          name: tailscale_${{env.RELEASE_VERSION}}_x86-64.apk
          path: tailscale_${{env.RELEASE_VERSION}}_x86-64.apk
